### ISSUE TITLE
Some weird behaviour in async

### ISSUE THREAD

**Issue by dselivanov** [r-lib/coro#29]
Hi @lionel- . Thanks for the great pkg!

I found some weird behaviour:
```r
async_test = function (seconds = 1) {
  promises::promise(function(resolve, reject) {
    later::later(~resolve(42L), delay = seconds)
  })
}

my_async = async(function() {
  res <- tryCatch(
    await(async_test()),
    error = function(err) NULL
  )
  message(res)
  res
})

p1 = my_async()
# 3
```
not sure why result is 3...

```r
my_async = async(function() {
  res <- await(async_test())
  message(res)
  res
})
p2 = my_async()
# 42
```
here 42 as expected

Apart from that if I use `=` as assignment (`res = await(async_test())`) then  `await` throws exception:

```r
my_async = async(function() {
  res = await(async_test())
  message(res)
  res
})
p2 = my_async()
#  Error: `await()` can't be called directly or within function arguments.
```

**Comment by lionel-** [comment]
You're right that's weird, I'll take a look thanks!

> if I use = as assignment (res = await(async_test())) then await throws exception:

ah I had totally forgotten about `=`, will fix.

**Comment by lionel-** [comment]
Should now be fixed, thanks for reporting.
