### ISSUE TITLE
Error when making generator a method of an R6 class

### ISSUE THREAD

**Issue by dfalbel** [r-lib/coro#30]
Not sure if you want to support that, but the following does not work:

``` r
g <- R6::R6Class(
  "generator",
  public = list(
    x = coro::generator(function() {
      for (i in 1:10)
        yield(i)
    })
  )
)

instance <- g$new()
instance$x
#> <generator>
#> Error in env_get(fn_env(x), "fn", inherit = TRUE): argument "default" is missing, with no default
instance$x()
#> Error in dots_split(..., .n_unnamed = 0:1): object '_parent' not found
```

R6 changes the function environments to the class env. It's probably also removing important information from the generator function.

**Comment by lionel-** [comment]
Maybe there should be a way of preventing R6 from treating a function as a method? For example functions wrapped in `I()`. And maybe functions with a custom class should automatically get that treatment?

What do you think @wch?

**Comment by lionel-** [comment]
In the meantime you can wrap the generators like this @dfalbel 

```r
R6::R6Class(
  "generator",
  private = list(
    generators = list(x = coro::generator(function() {
      for (i in 1:10)
        yield(i)
    }))
  ),
  public = list(
    x = function() private$generators$x()
  )
)
```

**Comment by dfalbel** [comment]
Thanks! That works great for me!

**Comment by wch** [comment]
With `R6Class`, all functions that are part of `public` or `private` are assumed to be methods, and their environment is modified when the class is instantiated.

R6 does have the notion of members function that are not methods, though. They must be assigned either in `initialize()` or after the object is created. So you could so something like this:

```R
num_generator <- coro::generator(function() {
  for (i in 1:10)
    yield(i)
})

Generator <- R6::R6Class(
  "Generator",
  public = list(
    initialize = function() {
      self$x = num_generator
    },
    x = NULL
  )
)
```

(You could also call `coro::generator(function() ....)` inside of `initialize()`, but that would create a new factory for each instance, which is less efficient.)

The difference between methods and non-method functions is recognized when the object is cloned; in the cloned object, methods will have their environment changed (so they can find the correct `self` and `private`), but non-method functions will not have their environment changed.

@lionel-, the idea of using `I()` to mark non-method functions is interesting. Want to file an issue on R6 so it can be discussed there? Or maybe the current behavior just needs to be better documented.

**Comment by lionel-** [comment]
Thanks for your input @wch!
I've filed an issue for `I()` at r-lib/R6#222.

Closing this since it's not a coro issue.
