### ISSUE TITLE
Yield in nested iterators

### ISSUE THREAD

**Issue by dfalbel** [r-lib/coro#31]
Is the following behaviour expected? I am trying to `yield` while iterating over a generator. Something like this, where `1:10` could be any `iterator` created with `as_iterator()`. 

``` r
library(coro)

g <- coro::generator(function() {
  coro::iterate(for (x in 1:10) {
    if (x < 5)
      yield(x)
    else
      yield(-1)
  })
})

g <- g()
g()
#> Error: `yield()` can't be called directly or within function arguments
```

<sup>Created on 2020-11-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by lionel-** [comment]
We should improve the error message. You don't need `iterate()` within generators, all `for` loops are instrumented so they support iterator functions.
