### ISSUE TITLE
Memory leak when a generator is created inside a function

### ISSUE THREAD

**Issue by dfalbel** [r-lib/coro#36]
It looks like that the function environment where the generator is created and used is never released, even if the generator itself is not in scope anymore.

Here's a reprex:

``` r
g <- function() {
  hello <- sample(1:1e7) # large object to easily verify the leak
  generate_abc <- coro::generator(function() {
    for (x in letters[1:3]) {
      coro::yield(x)
    }
  })
  coro::loop(for(x in generate_abc()) {
    y <- x
  })
}

for (x in 1:10) {
  g()
  gc()
  print(lobstr::mem_used())
}
#> 84,001,952 B
#> 124,300,760 B
#> 164,343,576 B
#> 204,386,400 B
#> 244,429,208 B
#> 284,472,048 B
#> 324,514,856 B
#> 364,557,664 B
#> 404,600,472 B
#> 444,643,344 B
```

**Comment by lionel-** [comment]
The leak occurred through an environment inlined in the body of generator instances. When the JIT compiles a function, it caches the bytecode in a hash table. The inlined environment was included in the constant pool of the bytecode and leaked through that cache. To fix this, we now inline a weak reference to the environment instead.

memtools failed to detect the leak because bytecode objects are not currently traversed. I've opened r-lib/memtools#1 to track this.

**Comment by dfalbel** [comment]
Thanks @lionel- ! That was tricky, I think I would never be able to figure this out :)

**Comment by lionel-** [comment]
No worries @dfalbel 
coro 1.0.2 is on CRAN. Sorry for the delay in treating this issue!

**Comment by randy3k** [comment]
Thanks. Just learn something today.

``` r
f <- function() {invisible(NULL)}
gc()
#>           used (Mb) gc trigger (Mb) limit (Mb) max used (Mb)
#> Ncells  641495 34.3    1335204 71.4         NA   936668 50.1
#> Vcells 1169576  9.0    8388608 64.0      16384  1889070 14.5
body(f)[[2]][[2]] <- sample(1e8)
# run f two times to tigger JIT
f()
f()
gc()
#>            used  (Mb) gc trigger  (Mb) limit (Mb)  max used  (Mb)
#> Ncells   642939  34.4    1335204  71.4         NA    936668  50.1
#> Vcells 51172974 390.5  123497824 942.3      16384 101215233 772.3
rm(f)
gc()
#>            used  (Mb) gc trigger  (Mb) limit (Mb)  max used  (Mb)
#> Ncells   642948  34.4    1335204  71.4         NA    936668  50.1
#> Vcells 51173004 390.5  123497824 942.3      16384 101215233 772.3
```

<sup>Created on 2021-12-04 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
