### ISSUE TITLE
How to pass rcmdcheck using generators

### ISSUE THREAD

**Issue by latot** [r-lib/coro#40]
Hi all, I'm trying to use generators inside a library, but after declaring a generator and using it this happens:

```R
f_iterator <- coro::generator(function(ret, from, to) {
    for (id in seq(length(from))){
      coro::yield(list(
        from = from[[id]],
        to = to[[id]],
        distance = ret[[id]]
      ))
    }
})
```

```R
  f_iterator : <anonymous>: no visible
    binding for global variable ‘generator_env’
  f_iterator : <anonymous>: no visible
    binding for global variable ‘exits’
  Undefined global functions or variables:
    exits generator_env id
```

What is the right way to handle this?

Usually, with rcmdcheck, use global variables are more like a workaround than a proper fix.

Thx!

**Comment by lionel-** [comment]
For now you'll need to use the `globalVariables()` workaround. We've working towards a better solution in https://bugs.r-project.org/show_bug.cgi?id=14354#c10
