### ISSUE TITLE
coro as an optional dependency

### ISSUE THREAD

**Issue by trangdata** [r-lib/coro#41]
Hi @lionel- Thanks for the awesome package! 🚀 

I have a question regarding adding coro to "Suggests" in my package openalexR. The idea is to allow the user to crawl through one OpenAlex record at a time ([PR](https://github.com/ropensci/openalexR/pull/184)). My current implementation is at https://github.com/ropensci/openalexR/blob/coro/R/coro.R. Do you have any suggestion on how to write tests for this generator function `oa_generate`? I tried using `skip_if_not_installed("coro")` and still getting errors...

The [test file](https://github.com/ropensci/openalexR/blob/coro/tests/testthat/test-coro.R) itself runs fine, but `devtools::check(cran = TRUE)` complains:
>    Error in oar() : could not find function "oar"
   Execution halted

Any advice is much appreciated! Thanks again! 💯

**Comment by lionel-** [comment]
Hi Trang,

This check runs at build-time not at run-time:

```r
oa_generate <- if (!requireNamespace("coro")) {
  message(
    "Package \"coro\" must be installed to use this generator."
  )
```

This might be the cause of the strange behaviour.

So I think you might need to wrap a coro generator like this:

```r
# Stateful environment for singletons
the <- new.env()

#' @export
oa_generate <- function(...) {
  rlang::check_installed("coro")

  if (is.null(the$oa_generate)) {
    the$oa_generate <- coro::generator(function(args) body))
  }

  the$oa_generate(...)
}
```

This way `oa_generate()` prompts the user to install coro if needed (or throws an error in non-interactive sessions), creates the generator and caches it for the next runs, and then forwards arguments.

**Comment by trangdata** [comment]
Exactly what I needed! Thank you so much Lionel!
