### ISSUE TITLE
Investigate failure with dev `evaluate()`

### ISSUE THREAD

**Issue by lionel-** [r-lib/coro#49]
With dev evaluate (https://github.com/r-lib/evaluate/issues/210), a bunch of snapshots fail with:

```
Error in `node_poke_cdr()`:
! bad value
```

Happens in the srcref handling in [block_states()](https://github.com/r-lib/coro/blob/a45f1f58f07d4b53ae76c5c9bcaeeaa961b28c95/R/parser.R#L327).

**Comment by hadley** [comment]
FYI I plan to submit on Monday Sept 16
